#!/usr/bin/env python3
"""
Lattice comparison v2 — proper construction.

For small N = pq, build:
  L_R: kernel of the map Z^d → (Z/NZ)*, (e₁,...,e_d) ↦ ∏ bᵢ^eᵢ mod N
  L_C: kernel of the map Z^d → Cl(Q(√N)), (e₁,...,e_d) ↦ ∏ [𝔭ᵢ]^eᵢ

These are properly lattices. We build them by finding a basis for each kernel.
"""

import math
import sys
import numpy as np
from fpylll import IntegerMatrix, LLL

sys.stdout.reconfigure(line_buffering=True)


def small_primes(limit):
    s = [True] * (limit + 1)
    s[0] = s[1] = False
    for i in range(2, int(limit**0.5) + 1):
        if s[i]:
            for j in range(i*i, limit + 1, i):
                s[j] = False
    return [i for i in range(limit + 1) if s[i]]


# =============================================================================
# Regev's lattice via discrete log
# =============================================================================

def build_regev_lattice_proper(N: int, p: int, q: int, bases: list) -> np.ndarray:
    """
    L_R = ker(φ: Z^d → (Z/NZ)*) where φ(e) = ∏ bᵢ^eᵢ mod N.

    By CRT: (Z/NZ)* ≅ (Z/pZ)* × (Z/qZ)*.
    So φ decomposes as φ_p × φ_q.

    To find the kernel, we compute discrete logs of each base mod p and mod q,
    then the kernel is {e : Σ eᵢ log_p(bᵢ) ≡ 0 mod (p-1) AND
                              Σ eᵢ log_q(bᵢ) ≡ 0 mod (q-1)}.

    This gives us L_R as the kernel of a matrix over Z.
    """
    d = len(bases)

    # Find a generator of (Z/pZ)* and (Z/qZ)*
    g_p = _primitive_root(p)
    g_q = _primitive_root(q)

    # Discrete logs of each base
    dlogs_p = []
    dlogs_q = []
    for b in bases:
        dlogs_p.append(_discrete_log(b % p, g_p, p))
        dlogs_q.append(_discrete_log(b % q, g_q, q))

    # The map φ in coordinates:
    # φ(e) = (Σ eᵢ·log_p(bᵢ) mod (p-1), Σ eᵢ·log_q(bᵢ) mod (q-1))
    #
    # The lattice L_R = {e ∈ Z^d : M·e ≡ 0 mod [p-1, q-1]}
    # where M is a 2×d matrix of discrete logs.
    #
    # We can build L_R as the kernel of this system using Smith normal form
    # or by constructing the lattice explicitly.

    # Build the augmented matrix:
    # [log_p(b1) log_p(b2) ... log_p(bd) | p-1  0  ]
    # [log_q(b1) log_q(b2) ... log_q(bd) |  0  q-1 ]
    # The kernel of the left part mod the right part.

    # Construct L_R using the HNF/Smith approach:
    # L_R is generated by:
    # 1. Vectors (0,...,0, p-1, 0,...,0) at each position (order of each base divides lcm)
    # 2. Vectors from the kernel computation

    # Actually, the cleanest way: L_R is the set of integer vectors e such that
    # the "log vector" (Σ eᵢ dlog_p(bᵢ), Σ eᵢ dlog_q(bᵢ)) lies in (p-1)Z × (q-1)Z.
    #
    # This is the preimage of {0} under Z^d → Z/(p-1) × Z/(q-1).
    # It's a lattice of rank d containing [(p-1)Z]^d but usually larger.

    # Build it as the row kernel of the matrix [dlog_p | dlog_q] mod [(p-1) | (q-1)]
    # Using the standard HNF kernel computation:

    # Augmented matrix A = [[dlogs_p[i] for i in d] [p-1 0]; [dlogs_q[i] for i in d] [0 q-1]]
    # size (2) × (d + 2)
    # Kernel = {e ∈ Z^d : A·[e; k] = 0 for some k ∈ Z^2}
    # = {e ∈ Z^d : ∃ k₁,k₂ s.t. Σ eᵢ dlog_p(bᵢ) + k₁(p-1) = 0 AND
    #                               Σ eᵢ dlog_q(bᵢ) + k₂(q-1) = 0}

    # Construct via LLL on the augmented lattice
    # Rows of basis matrix B (size (d+2) × (d+2)):
    # First d rows: [I_d | A^T] where A is the dlog matrix
    # Last 2 rows: [0 | diag(p-1, q-1)] scaled

    # Simpler approach: enumerate short vectors in the lattice
    # defined by M·e ≡ 0 mod [p-1, q-1] using HNF

    # Build the lattice basis using the modular constraint approach:
    # Basis for L_R:
    # Row i (for i < d): e_i (unit vector) scaled by appropriate amount
    # Plus modular constraints

    # The standard construction: lattice L is generated by the rows of
    # [p-1  0   dlp_0  dlp_1 ... dlp_{d-1}]
    # [ 0  q-1  dlq_0  dlq_1 ... dlq_{d-1}]
    # [          (p-1)*I_d                  ]
    # ... no, this mixes things up.

    # Let me just use the direct approach:
    # M = 2×d matrix of discrete logs: M[0][i] = dlog_p(b_i), M[1][i] = dlog_q(b_i)
    # L_R = {e ∈ Z^d : M*e ∈ (p-1)Z × (q-1)Z}

    # This is the lattice generated by:
    # - All vectors e where M*e = (p-1)*f₁ for some integer f₁ (first constraint)
    # intersected with
    # - All vectors e where M*e = (q-1)*f₂ for some integer f₂ (second constraint)

    # Build via HNF: the lattice L_R has a basis computable from the
    # Smith Normal Form of M mod [(p-1), (q-1)].

    # For our purposes (small d), just build the kernel numerically:
    # Generate candidate vectors and test them

    # PRACTICAL: use numpy to find the kernel over Z
    # The kernel of M mod [p-1, q-1] can be found by:
    # 1. Finding the kernel of M over Q (continuous kernel)
    # 2. Intersecting with Z^d
    # 3. Adding modular constraint vectors

    # Step 1: Build the full integer lattice
    # Basis: columns of the matrix whose rows span L_R
    # This is the lattice with basis given by the HNF of:
    # [M^T | diag(p-1, q-1)]^T applied appropriately

    # Let me use the standard "modular lattice" construction:
    dim = d + 2
    B = IntegerMatrix(dim, dim)

    # First d rows: identity, representing the exponent vector
    for i in range(d):
        B[i, i] = 1
    # Constraint rows: the discrete log constraints (scaled)
    for i in range(d):
        B[i, d] = dlogs_p[i]
        B[i, d + 1] = dlogs_q[i]
    # Modular constraint rows
    B[d, d] = p - 1
    B[d + 1, d + 1] = q - 1

    # LLL reduce
    LLL.reduction(B)

    # Extract vectors where the last 2 coordinates are 0 (or small)
    # These are the actual L_R vectors
    kernel_vecs = []
    for i in range(dim):
        v = [int(B[i, j]) for j in range(d)]
        aux = [int(B[i, j]) for j in range(d, dim)]
        # If auxiliary coordinates are 0, this is in the kernel
        if all(a == 0 for a in aux):
            if any(x != 0 for x in v):
                kernel_vecs.append(v)

    return kernel_vecs, dlogs_p, dlogs_q


def build_class_lattice_proper(N: int, p: int, q: int, bases: list) -> list:
    """
    L_C = ker(ψ: Z^d → Cl(Q(√N))) where ψ(e) = ∏ [𝔭ᵢ]^eᵢ.

    For N = pq with discriminant Δ = 4N:
    - The class group Cl(Δ) has a 2-torsion subgroup of rank 1
    - The genus map: Cl → {±1} is given by the Jacobi symbol character
    - The kernel of the genus map = principal genus

    For each base prime ℓ that splits:
      ℓ splits as 𝔭·𝔭' where 𝔭 = (ℓ, r + √N) for r² ≡ N mod ℓ.
      The class [𝔭] has a genus determined by (ℓ/p) (Legendre symbol).

    A relation ∏ [𝔭ᵢ]^eᵢ = [1] means the ideal product is principal.
    This is EQUIVALENT to the exponent vector being in L_R
    PLUS the additional condition that the norm equation has a solution.

    The key structural difference:
    L_R captures: ∏ bᵢ^eᵢ ≡ 1 mod N
    L_C captures: ∏ bᵢ^eᵢ ≡ α² mod N for some α (the ideal is principal
                  iff the element is a norm from Q(√N))

    So L_C ⊆ L_R (every class group relation is a multiplicative relation)
    but L_R might be strictly larger (has relations that aren't norm-relations).
    """
    d = len(bases)

    # The genus character for discriminant 4N = 4pq:
    # χ(form) = (a/p) where a is the first coefficient of a form in the class
    # For a splitting prime ℓ with form (ℓ, b, c):
    # χ(ℓ) = (ℓ/p) = Legendre symbol

    genus_chars = []
    for b in bases:
        if p > 2 and b != p:
            genus_chars.append(pow(b, (p - 1) // 2, p))  # 1 or p-1 (= -1 mod p)
        else:
            genus_chars.append(1)

    # Convert to ±1
    genus = []
    for g, b in zip(genus_chars, bases):
        if g == 1:
            genus.append(0)  # in principal genus (QR mod p)
        else:
            genus.append(1)  # in non-principal genus (QNR mod p)

    # A class group relation ∏ [𝔭ᵢ]^eᵢ = [1] requires:
    # 1. ∏ bᵢ^eᵢ ≡ 1 mod N (it's a multiplicative relation)
    # 2. Σ eᵢ·genus[i] ≡ 0 mod 2 (the product is in the principal genus)

    # So L_C = L_R ∩ {e : Σ eᵢ·genus[i] ≡ 0 mod 2}
    # This is L_R intersected with a codimension-1 sublattice (the genus constraint)!

    return genus


# =============================================================================
# Main comparison
# =============================================================================

def compare(N, p, q, num_primes=6):
    print(f"\n{'='*70}")
    print(f"  N = {N} = {p} × {q} ({N.bit_length()} bits)")
    print(f"{'='*70}")

    bases = [pr for pr in small_primes(50) if N % pr != 0][:num_primes]
    d = len(bases)
    print(f"  Bases: {bases}")

    # Build Regev lattice
    kernel_R, dlogs_p, dlogs_q = build_regev_lattice_proper(N, p, q, bases)
    print(f"\n  L_R (Regev): {len(kernel_R)} kernel vectors found")
    for v in kernel_R[:8]:
        norm = math.sqrt(sum(x*x for x in v))
        # Verify: ∏ bases[i]^v[i] ≡ 1 mod N
        prod = 1
        for i, e in enumerate(v):
            if e >= 0:
                prod = (prod * pow(bases[i], e, N)) % N
            else:
                prod = (prod * pow(bases[i], -e, N)) % N
                prod = pow(prod, -1, N) if math.gcd(prod, N) == 1 else 0
        # Simpler verification using dlogs
        check_p = sum(v[i] * dlogs_p[i] for i in range(d)) % (p - 1)
        check_q = sum(v[i] * dlogs_q[i] for i in range(d)) % (q - 1)
        ok = "✓" if (check_p == 0 and check_q == 0) else "✗"
        print(f"    {v}  norm={norm:.2f}  {ok}")

    # Build class group genus constraint
    genus = build_class_lattice_proper(N, p, q, bases)
    print(f"\n  Genus characters (ℓ/p): {genre_str(bases, genus)}")

    # L_C = L_R ∩ {e : Σ eᵢ genus[i] ≡ 0 mod 2}
    kernel_C = [v for v in kernel_R if sum(v[i] * genus[i] for i in range(d)) % 2 == 0]
    kernel_C_complement = [v for v in kernel_R if sum(v[i] * genus[i] for i in range(d)) % 2 == 1]

    print(f"\n  L_C (Class group): {len(kernel_C)} vectors (genus-even)")
    for v in kernel_C[:5]:
        norm = math.sqrt(sum(x*x for x in v))
        print(f"    {v}  norm={norm:.2f}")

    print(f"\n  L_R \\ L_C: {len(kernel_C_complement)} vectors (genus-odd)")
    for v in kernel_C_complement[:5]:
        norm = math.sqrt(sum(x*x for x in v))
        print(f"    {v}  norm={norm:.2f}")

    # THE KEY STRUCTURAL INSIGHT:
    # L_R has index 2 in L_C (genus is a mod-2 constraint)
    # So L_C ⊂ L_R with [L_R : L_C] = 2
    # Actually it's the OTHER way: L_C ⊂ L_R
    # L_C = {e ∈ L_R : genus parity = 0}

    print(f"\n  STRUCTURAL RESULT:")
    print(f"  L_C = L_R ∩ (genus hyperplane)")
    print(f"  [L_R : L_C] = 2 (genus theory: 2 genera for N=pq)")
    print(f"  L_R \\ L_C contains vectors where ∏ bᵢ^eᵢ ≡ 1 mod N")
    print(f"  but the product is a QNR mod p (and QR mod q, or vice versa).")

    # Factor revelation via genus-odd vectors
    print(f"\n  --- Factor revelation test ---")
    for v in kernel_R:
        # For each relation, try the gcd trick
        # Compute x = ∏ bases[i]^(v[i]/2) if all even
        if all(e % 2 == 0 for e in v) and any(e != 0 for e in v):
            half = 1
            for i, e in enumerate(v):
                if e > 0:
                    half = (half * pow(bases[i], e // 2, N)) % N
                elif e < 0:
                    inv = pow(bases[i], -e // 2, N)
                    half = (half * pow(inv, -1, N)) % N if math.gcd(inv, N) == 1 else 0
            g1 = math.gcd(half - 1, N)
            g2 = math.gcd(half + 1, N)
            genus_val = sum(v[i] * genus[i] for i in range(d)) % 2
            tag = "genus-even (L_C)" if genus_val == 0 else "GENUS-ODD (L_R\\L_C)"
            if 1 < g1 < N or 1 < g2 < N:
                factor = g1 if 1 < g1 < N else g2
                print(f"    {v} → FACTOR {factor}!  [{tag}]")
            else:
                print(f"    {v} → no factor  [{tag}]")

    # The deep question: genus-odd vectors in L_R should reveal factors
    # because they correspond to x with x ≡ QR mod p, x ≡ QNR mod q
    # So x^((p-1)/2) ≡ 1 mod p but x^((q-1)/2) ≡ -1 mod q
    # Meaning gcd(x^((N-1)/2) ± 1, N) might factor!
    print(f"\n  --- Genus-odd Euler criterion test ---")
    for v in kernel_C_complement[:5]:
        # Compute x = ∏ bases[i]^v[i] mod N (this should be 1 by construction)
        # But the HALF-product ∏ bases[i]^(v[i]) is in L_R, meaning it's ≡ 1 mod N
        # The genus-odd property means the "path" to 1 goes through different
        # quadratic residuosity mod p vs q
        # Can we exploit this without computing the half-product?

        # Try: compute ∏ bases[i]^|v[i]| mod p and mod q separately
        # This requires knowing p, q — but the POINT is to see if the
        # lattice structure itself encodes the difference
        prod_mod_p = 1
        prod_mod_q = 1
        for i, e in enumerate(v):
            prod_mod_p = (prod_mod_p * pow(bases[i] % p, e % (p-1), p)) % p
            prod_mod_q = (prod_mod_q * pow(bases[i] % q, e % (q-1), q)) % q
        print(f"    {v}: mod p={prod_mod_p}, mod q={prod_mod_q}")


def genre_str(bases, genus):
    return ", ".join(f"({b}/p)={'QR' if g==0 else 'QNR'}" for b, g in zip(bases, genus))


def _primitive_root(p):
    """Find a primitive root mod prime p."""
    if p == 2:
        return 1
    phi = p - 1
    factors = _factorize_small(phi)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in factors):
            return g
    return None


def _discrete_log(a, g, p):
    """Compute log_g(a) mod (p-1) by brute force."""
    a = a % p
    if a == 0:
        return 0
    current = 1
    for k in range(p):
        if current == a:
            return k
        current = (current * g) % p
    return 0


def _factorize_small(n):
    """Return set of prime factors of n."""
    factors = set()
    d = 2
    while d * d <= n:
        while n % d == 0:
            factors.add(d)
            n //= d
        d += 1
    if n > 1:
        factors.add(n)
    return factors


if __name__ == "__main__":
    for p, q in [(7, 11), (13, 17), (23, 29), (101, 103), (211, 223), (541, 631)]:
        compare(p * q, p, q, num_primes=6)
