#!/usr/bin/env python3
"""
QUANTUM MICROSCOPE: Look at what Regev's algorithm actually produces.

For small N = pq, simulate the full quantum output:
  1. Build L_R (multiplicative relation lattice) explicitly
  2. Compute L* (dual lattice) explicitly
  3. Enumerate ALL elements of L*/Z^d — the finite group the quantum circuit samples from
  4. STARE at them. What do they look like? Coordinates, distribution, structure.
  5. Ask: is there ANYTHING about these samples computable from N without knowing p?

This isn't trying to factor N. It's trying to understand what quantum gets you,
at a scale where you can see every number.
"""

import math
import random
import sys
import numpy as np
from itertools import product as iproduct
from collections import Counter

sys.stdout.reconfigure(line_buffering=True)


# =========================================================================
# Helpers
# =========================================================================

def small_primes(limit):
    s = [True] * (limit + 1)
    s[0] = s[1] = False
    for i in range(2, int(limit**0.5) + 1):
        if s[i]:
            for j in range(i*i, limit + 1, i):
                s[j] = False
    return [i for i in range(limit + 1) if s[i]]


def primitive_root(p):
    if p == 2: return 1
    phi = p - 1
    factors = set()
    n = phi
    d = 2
    while d * d <= n:
        while n % d == 0: factors.add(d); n //= d
        d += 1
    if n > 1: factors.add(n)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in factors):
            return g
    return None


def discrete_log(a, g, p):
    a = a % p
    if a == 0: return 0
    cur = 1
    for k in range(p):
        if cur == a: return k
        cur = (cur * g) % p
    return 0


# =========================================================================
# Build L_R and L* explicitly
# =========================================================================

def build_lattices(N, p, q, d=None):
    """
    Build L_R and L* for N = pq with d-dimensional factor base.

    L_R = {e ∈ Z^d : ∏ b_i^{e_i} ≡ 1 mod N}
    L* = dual lattice = {w ∈ R^d : <w, e> ∈ Z for all e ∈ L_R}
    L*/Z^d = finite group of order det(L_R)

    Returns: bases list, L_R basis, L* basis, elements of L*/Z^d
    """
    primes = [pr for pr in small_primes(200) if N % pr != 0]
    if d is None:
        d = min(len(primes), 8)
    bases = primes[:d]

    # Compute discrete logs
    g_p = primitive_root(p)
    g_q = primitive_root(q)
    dlp = [discrete_log(b % p, g_p, p) for b in bases]
    dlq = [discrete_log(b % q, g_q, q) for b in bases]

    # Genus character
    genus = [dl % 2 for dl in dlp]

    # Build L_R via augmented lattice + LLL
    from fpylll import IntegerMatrix, LLL

    dim = d + 2
    B = IntegerMatrix(dim, dim)
    for i in range(d):
        B[i, i] = 1
        B[i, d] = dlp[i]
        B[i, d + 1] = dlq[i]
    B[d, d] = p - 1
    B[d + 1, d + 1] = q - 1

    LLL.reduction(B)

    # Extract kernel vectors (auxiliary coords = 0)
    kernel_vecs = []
    for i in range(dim):
        v = np.array([int(B[i, j]) for j in range(d)])
        aux = [int(B[i, j]) for j in range(d, dim)]
        if all(a == 0 for a in aux) and np.any(v != 0):
            kernel_vecs.append(v)

    if len(kernel_vecs) == 0:
        return None

    # L_R basis matrix (rows = basis vectors)
    B_LR = np.array(kernel_vecs, dtype=np.float64)
    rank = B_LR.shape[0]

    # Compute L* basis: if B_LR is rank x d, then L* has a basis
    # L* = {w : B_LR @ w ∈ Z^rank}
    # A basis for L* (as a d-dimensional lattice containing Z^d):
    # L* is generated by Z^d plus vectors that map to the dual of B_LR

    # For L*/Z^d: this is isomorphic to Z^rank / (B_LR^T @ Z^d ∩ Z^rank)
    # More precisely: L*/Z^d ≅ Z^d / L_R
    # Wait, that's not right either. Let me think carefully.

    # L_R is a sublattice of Z^d. The dual lattice L* contains Z^d.
    # L*/Z^d is a finite group of order det(L_R) (when L_R has full rank in some sense).

    # Actually, for the quotient group that Regev samples from:
    # The quantum circuit samples from the cosets of Z^d in L*.
    # |L*/Z^d| = |Z^d/L_R| = det(L_R) (the index of L_R in Z^d).

    # But L_R has rank < d typically. So the quotient is infinite in some directions.
    # Regev's algorithm works in the quotient R^d/Z^d (the d-torus),
    # and L*/Z^d is a finite subset of this torus when projected to the
    # subspace spanned by L_R.

    # Let me compute this more carefully.
    # L_R has rank r and lives in Z^d.
    # L* = {w ∈ R^d : <w, x> ∈ Z for all x ∈ L_R}
    # Since L_R ⊂ Z^d, we have Z^d ⊂ L* (because <z, x> ∈ Z for z ∈ Z^d, x ∈ Z^d).
    # L*/Z^d is a finite group of order det(Smith normal form of B_LR) when rank = r.

    # To enumerate L*/Z^d:
    # Let B_LR be the r x d integer matrix of L_R basis vectors.
    # Compute Smith Normal Form: U @ B_LR @ V = S where S is diagonal.
    # Then L*/Z^d ≅ Z/s_1 x Z/s_2 x ... x Z/s_r (s_i are diagonal entries of S).
    # The elements can be enumerated as (k_1/s_1, ..., k_r/s_r) in appropriate coordinates.

    # Use numpy for SNF (approximate, then round)
    # Actually, let's use a direct approach: find the quotient group.

    # The Smith Normal Form of an integer matrix:
    B_int = np.array(kernel_vecs, dtype=np.int64)

    # Simple SNF for small matrices
    snf_diag, U, V = smith_normal_form(B_int)

    return {
        'bases': bases,
        'd': d,
        'rank': rank,
        'B_LR': B_int,
        'kernel_vecs': kernel_vecs,
        'genus': genus,
        'dlp': dlp,
        'dlq': dlq,
        'snf': snf_diag,
        'U': U,
        'V': V,
        'p': p,
        'q': q,
        'N': N,
    }


def smith_normal_form(M):
    """
    Compute the Smith Normal Form of integer matrix M.
    Returns (diagonal, U, V) where U @ M @ V = diag(diagonal).
    """
    M = np.array(M, dtype=np.int64).copy()
    r, c = M.shape
    U = np.eye(r, dtype=np.int64)
    V = np.eye(c, dtype=np.int64)

    for k in range(min(r, c)):
        # Find pivot
        found = False
        for i in range(k, r):
            for j in range(k, c):
                if M[i, j] != 0:
                    # Swap rows k, i
                    if i != k:
                        M[[k, i]] = M[[i, k]]
                        U[[k, i]] = U[[i, k]]
                    # Swap cols k, j
                    if j != k:
                        M[:, [k, j]] = M[:, [j, k]]
                        V[:, [k, j]] = V[:, [j, k]]
                    found = True
                    break
            if found:
                break
        if not found:
            break

        # Reduce using the pivot
        changed = True
        while changed:
            changed = False
            # Row operations
            for i in range(k + 1, r):
                if M[i, k] != 0:
                    q = M[i, k] // M[k, k]
                    M[i] -= q * M[k]
                    U[i] -= q * U[k]
                    if M[i, k] != 0:
                        # Need to use extended gcd
                        g, s, t = extended_gcd(int(M[k, k]), int(M[i, k]))
                        a, b = int(M[k, k]) // g, int(M[i, k]) // g
                        new_k = s * M[k] + t * M[i]
                        new_i = -b * M[k] + a * M[i]
                        M[k] = new_k
                        M[i] = new_i
                        new_uk = s * U[k] + t * U[i]
                        new_ui = -b * U[k] + a * U[i]
                        U[k] = new_uk
                        U[i] = new_ui
                        changed = True
            # Column operations
            for j in range(k + 1, c):
                if M[k, j] != 0:
                    q = M[k, j] // M[k, k]
                    M[:, j] -= q * M[:, k]
                    V[:, j] -= q * V[:, k]
                    if M[k, j] != 0:
                        g, s, t = extended_gcd(int(M[k, k]), int(M[k, j]))
                        a, b = int(M[k, k]) // g, int(M[k, j]) // g
                        new_k = s * M[:, k] + t * M[:, j]
                        new_j = -b * M[:, k] + a * M[:, j]
                        M[:, k] = new_k
                        M[:, j] = new_j
                        new_vk = s * V[:, k] + t * V[:, j]
                        new_vj = -b * V[:, k] + a * V[:, j]
                        V[:, k] = new_vk
                        V[:, j] = new_vj
                        changed = True

    # Make diagonal positive
    diag = []
    for k in range(min(r, c)):
        if M[k, k] < 0:
            M[k] = -M[k]
            U[k] = -U[k]
        diag.append(int(M[k, k]))

    return diag, U, V


def extended_gcd(a, b):
    if b == 0:
        return a, 1, 0
    g, s, t = extended_gcd(b, a % b)
    return g, t, s - (a // b) * t


# =========================================================================
# Enumerate L*/Z^d explicitly
# =========================================================================

def enumerate_dual_quotient(info):
    """
    Enumerate all elements of L*/Z^d (the group the quantum circuit samples from).

    Using Smith Normal Form: if B_LR has SNF diag (s_1, ..., s_r), then
    L*/Z^d ≅ Z/s_1 x ... x Z/s_r

    The elements in the original coordinates are:
    v_k = V @ (k_1/s_1, ..., k_r/s_r, 0, ..., 0)^T  mod Z^d
    for k_i = 0, ..., s_i - 1
    """
    snf = info['snf']
    V = info['V']
    d = info['d']
    rank = info['rank']

    # Filter out zero diagonal entries
    nonzero_snf = [(i, s) for i, s in enumerate(snf) if s > 0]

    if not nonzero_snf:
        return np.array([[0.0] * d])

    # Total number of elements
    total = 1
    for _, s in nonzero_snf:
        total *= s

    if total > 100000:
        print(f"  WARNING: L*/Z^d has {total} elements, sampling instead of enumerating")
        # Sample uniformly
        elements = []
        for _ in range(min(10000, total)):
            coords = np.zeros(d, dtype=np.float64)
            for idx, s in nonzero_snf:
                k = random.randint(0, s - 1)
                coords += (k / s) * V[:, idx].astype(np.float64)
            coords = coords % 1.0
            elements.append(coords)
        return np.array(elements)

    # Enumerate all elements
    ranges = [range(s) for _, s in nonzero_snf]
    elements = []

    for combo in iproduct(*ranges):
        coords = np.zeros(d, dtype=np.float64)
        for (idx, s), k in zip(nonzero_snf, combo):
            coords += (k / s) * V[:, idx].astype(np.float64)
        coords = coords % 1.0
        # Shift to [-0.5, 0.5)
        coords = coords - np.floor(coords + 0.5)
        coords = coords % 1.0  # back to [0, 1)
        elements.append(coords)

    return np.array(elements)


# =========================================================================
# ANALYSIS: What do these quantum samples look like?
# =========================================================================

def analyze_quantum_samples(info, elements):
    """Deep analysis of the quantum samples (elements of L*/Z^d)."""

    N = info['N']
    p = info['p']
    q = info['q']
    d = info['d']
    bases = info['bases']
    genus = info['genus']
    dlp = info['dlp']
    dlq = info['dlq']
    snf = info['snf']

    n_elements = len(elements)

    print(f"\n  N = {N} = {p} × {q}  ({N.bit_length()} bits)")
    print(f"  Factor base: {bases}  (d = {d})")
    print(f"  L_R rank: {info['rank']}")
    print(f"  SNF diagonal: {snf}")
    print(f"  |L*/Z^d| = {n_elements}")
    print(f"  Genus character ε: {genus}")

    # ---- STRUCTURE OF THE GROUP ----
    print(f"\n  --- Group structure ---")
    nonzero_snf = [s for s in snf if s > 0]
    group_str = " × ".join(f"Z/{s}" for s in nonzero_snf)
    print(f"  L*/Z^d ≅ {group_str}")

    # ---- COORDINATE ANALYSIS ----
    print(f"\n  --- Coordinate analysis ---")
    print(f"  Each element is a point in [0,1)^{d} (the d-torus)")

    # What values does each coordinate take?
    for i in range(d):
        vals = sorted(set(round(float(e), 10) for e in elements[:, i]))
        n_distinct = len(vals)
        print(f"  coord {i} (base {bases[i]}): {n_distinct} distinct values", end="")
        if n_distinct <= 20:
            # Show the actual values as fractions
            fracs = []
            for v in vals:
                # Try to express as a/b
                best_frac = None
                for denom in range(1, max(snf) + 1 if snf else 2):
                    numer = round(v * denom)
                    if abs(v - numer/denom) < 1e-6:
                        best_frac = f"{numer}/{denom}" if numer != 0 else "0"
                        break
                fracs.append(best_frac if best_frac else f"{v:.4f}")
            print(f"  values: {fracs}")
        else:
            print(f"  (range: [{min(vals):.4f}, {max(vals):.4f}])")

    # ---- RELATIONSHIP TO p AND q ----
    print(f"\n  --- Relationship to p, q ---")

    # Key question: do the coordinates encode information about p?
    # The dual lattice L* is determined by L_R, which depends on the discrete logs.
    # The discrete logs mod p encode the Legendre symbols (b_i/p).
    # So L*/Z^d encodes (b_i/p) for all bases — which IS the factoring secret.

    # But HOW is it encoded? Let's see.
    # L_R is defined by: Σ e_i · dlog_p(b_i) ≡ 0 (mod p-1) AND Σ e_i · dlog_q(b_i) ≡ 0 (mod q-1)
    # So L_R depends on the discrete logs mod p and mod q.
    # L* depends on L_R.
    # The elements of L*/Z^d are the cosets.

    # Can we recover the discrete logs from the elements of L*/Z^d?
    # The elements w ∈ L*/Z^d satisfy: <w, e> ∈ Z for all e ∈ L_R.
    # Equivalently: B_LR @ w ∈ Z^rank.

    # The coordinates of w are related to the inverse of B_LR.

    # Let's check: for each element, compute B_LR @ w mod 1
    B_LR = info['B_LR'].astype(np.float64)
    for i, w in enumerate(elements[:5]):
        prod = B_LR @ w
        prod_frac = prod - np.round(prod)
        print(f"  w[{i}] = {np.round(w, 4)}  →  B_LR @ w mod 1 = {np.round(prod_frac, 6)}")

    # ---- THE DEEP QUESTION ----
    print(f"\n  --- The deep question ---")
    print(f"  L*/Z^d is determined by L_R, which is determined by (p, q).")
    print(f"  The quantum circuit samples UNIFORMLY from L*/Z^d.")
    print(f"  Can ANYTHING about L*/Z^d be computed from N alone?")

    # Test 1: Can we compute |L*/Z^d| from N?
    # |L*/Z^d| = det(L_R) = product of SNF diagonal entries
    det_LR = 1
    for s in snf:
        if s > 0:
            det_LR *= s
    print(f"\n  Test 1: |L*/Z^d| = det(L_R) = {det_LR}")
    print(f"    (p-1)(q-1) = {(p-1)*(q-1)}")
    print(f"    lcm(p-1,q-1) = {(p-1)*(q-1)//math.gcd(p-1,q-1)}")
    print(f"    Relation: det(L_R) is related to the structure of (Z/NZ)*")

    # Test 2: The coordinates of L*/Z^d elements as rational numbers
    # What denominators appear?
    print(f"\n  Test 2: Denominators in L*/Z^d coordinates")
    all_denoms = set()
    for w in elements:
        for v in w:
            # Find smallest denominator
            for denom in range(1, 10000):
                if abs(v * denom - round(v * denom)) < 1e-6:
                    all_denoms.add(denom)
                    break
    print(f"    Denominators that appear: {sorted(all_denoms)[:20]}")
    print(f"    These should divide the SNF entries: {nonzero_snf}")

    # Test 3: Projection onto genus direction
    print(f"\n  Test 3: Genus structure of L*/Z^d")
    genus_vec = np.array(genus, dtype=np.float64)
    if np.linalg.norm(genus_vec) > 0:
        projections = elements @ genus_vec
        proj_mod1 = projections % 1.0
        proj_values = sorted(set(round(float(v), 8) for v in proj_mod1))
        print(f"    Projection of L*/Z^d onto genus direction ε:")
        if len(proj_values) <= 30:
            for v in proj_values:
                count = sum(1 for pv in proj_mod1 if abs(pv - v) < 1e-6)
                # Express as fraction
                for denom in range(1, max(snf) + 1 if snf else 2):
                    numer = round(v * denom)
                    if abs(v - numer/denom) < 1e-6:
                        frac = f"{numer}/{denom}"
                        break
                else:
                    frac = f"{v:.6f}"
                print(f"      {frac}: {count} elements")
        print(f"    The genus character splits L*/Z^d into even/odd halves.")
        print(f"    Only genus-ODD samples lead to factoring.")
        print(f"    But which half is which requires knowing ε = ((b_i/p)+1)/2,")
        print(f"    which requires knowing p.")

    # Test 4: What do the elements look like modulo small integers?
    print(f"\n  Test 4: Elements mod small integers")
    for m in [2, 3, 4, 6]:
        coords_mod_m = np.round(elements * m) % m
        unique_patterns = set(tuple(int(x) for x in row) for row in coords_mod_m)
        print(f"    mod {m}: {len(unique_patterns)} distinct patterns out of {m**d} possible")

    # Test 5: Are some coordinates predictable from N alone?
    # The Jacobi symbol (b_i/N) is computable without knowing p.
    # It equals (b_i/p)(b_i/q). If (b_i/N) = -1, we know (b_i/p) ≠ (b_i/q).
    # If (b_i/N) = 1, we know (b_i/p) = (b_i/q) but not which.
    print(f"\n  Test 5: Jacobi symbols (computable from N)")
    for i, b in enumerate(bases):
        j_symbol = jacobi_sym(b, N)
        leg_p = 1 if dlp[i] % 2 == 0 else -1
        leg_q = 1 if dlq[i] % 2 == 0 else -1
        print(f"    ({b}/N) = {j_symbol:+d}  "
              f"({b}/p) = {leg_p:+d}  ({b}/q) = {leg_q:+d}  "
              f"ε_{i} = {genus[i]}")

    # Test 6: The SPACING between elements
    print(f"\n  Test 6: Spacing between consecutive elements (1D projection)")
    if n_elements > 1 and n_elements < 10000:
        # Project onto first coordinate
        coord0 = sorted(elements[:, 0] % 1.0)
        spacings = [coord0[i+1] - coord0[i] for i in range(len(coord0)-1)]
        if spacings:
            mean_sp = np.mean(spacings)
            std_sp = np.std(spacings)
            print(f"    Mean spacing: {mean_sp:.6f} (expected 1/{n_elements} = {1/n_elements:.6f})")
            print(f"    Std of spacing: {std_sp:.6f}")
            print(f"    Min spacing: {min(spacings):.6f}")
            print(f"    Max spacing: {max(spacings):.6f}")
            print(f"    Spacing ratio (max/min): {max(spacings)/min(spacings):.2f}" if min(spacings) > 0 else "")

    # Test 7: Reconstruct L_R from L*/Z^d (this is what LLL does)
    print(f"\n  Test 7: Can we reconstruct L_R from L*/Z^d?")
    print(f"    Given {n_elements} elements of L*/Z^d, LLL on the dual")
    print(f"    recovers L_R. This is exactly Regev's classical post-processing.")
    print(f"    The quantum advantage is PRODUCING the {n_elements} elements.")

    return elements


def jacobi_sym(a, n):
    if n <= 0 or n % 2 == 0: return 0
    a = a % n
    result = 1
    while a != 0:
        while a % 2 == 0:
            a //= 2
            if n % 8 in (3, 5): result = -result
        a, n = n, a
        if a % 4 == 3 and n % 4 == 3: result = -result
        a = a % n
    return result if n == 1 else 0


# =========================================================================
# COMPARISON: Classical processes vs quantum samples
# =========================================================================

def compare_classical_to_quantum(info, quantum_elements):
    """
    For each classical sampling strategy, see how close its output
    is to the actual quantum samples (elements of L*/Z^d).
    """
    N = info['N']
    d = info['d']
    bases = info['bases']

    print(f"\n  --- Classical vs Quantum comparison ---")

    B_LR = info['B_LR'].astype(np.float64)

    # The "correct" samples are the quantum_elements.
    # A classical strategy produces vectors w ∈ [0,1)^d.
    # We measure: min distance from each classical sample to any quantum element.

    n_samples = min(1000, len(quantum_elements) * 10)

    strategies = {}

    # Strategy: Uniform random (baseline)
    uniform = np.random.rand(n_samples, d)
    strategies['uniform'] = uniform

    # Strategy: Use Jacobi symbols to guess
    # (b_i/N) tells us if (b_i/p) = (b_i/q).
    # If (b_i/N) = 1 and b_i is small, likely QR mod both.
    # Use this to guess genus character → guess coordinates.
    jacobi_guesses = np.random.rand(n_samples, d)
    for i, b in enumerate(bases):
        j = jacobi_sym(b, N)
        if j == 1:
            # Guess: b is QR mod both p and q, so genus[i] = 0
            # This constrains the i-th coordinate of L*/Z^d elements
            pass  # Hard to translate genus into coordinate values without more info
    strategies['jacobi_guess'] = jacobi_guesses

    # Strategy: Random lattice-structured points
    # Generate random integer vectors, project via (B_LR^{-T})
    # This produces points in L* but not necessarily in L*/Z^d
    if info['rank'] > 0:
        # Random integer vectors of length rank
        rand_ints = np.random.randint(-10, 11, size=(n_samples, info['rank']))
        # Project: each row r gives w = V @ (r_1/s_1, ..., r_r/s_r, 0, ..., 0)
        # But we don't know the SNF from N alone!
        pass

    # Strategy: Evaluate specific functions of N at the base primes
    # For each base b_i, compute b_i^{(N-1)/2} mod N (Euler criterion)
    euler_vals = []
    for b in bases:
        e = pow(b, (N - 1) // 2, N)
        euler_vals.append(e / N)  # Normalize to [0, 1)
    euler_samples = np.tile(euler_vals, (n_samples, 1))
    euler_samples += np.random.randn(n_samples, d) * 0.01  # Small noise
    euler_samples = euler_samples % 1.0
    strategies['euler'] = euler_samples

    # Strategy: Power residues — b_i^k mod N for various k
    power_samples = np.zeros((n_samples, d))
    for s in range(n_samples):
        k = random.randint(1, N)
        for i, b in enumerate(bases):
            power_samples[s, i] = pow(b, k, N) / N
    strategies['power_residue'] = power_samples

    # Measure quality: for each strategy, what fraction of samples
    # land close to a quantum element?
    print(f"  Quality metric: fraction of classical samples within δ of a quantum element")
    print(f"  (δ thresholds: 0.01, 0.05, 0.10)")

    for name, samples in strategies.items():
        # For each classical sample, find distance to nearest quantum element
        min_dists = []
        for s in samples[:200]:  # Limit for speed
            # Distance on torus
            diffs = quantum_elements - s[np.newaxis, :]
            diffs = diffs - np.round(diffs)  # Wrap to [-0.5, 0.5)
            dists = np.sqrt(np.sum(diffs**2, axis=1))
            min_dists.append(np.min(dists))

        mean_dist = np.mean(min_dists)
        frac_01 = np.mean(np.array(min_dists) < 0.01)
        frac_05 = np.mean(np.array(min_dists) < 0.05)
        frac_10 = np.mean(np.array(min_dists) < 0.10)

        print(f"    {name:20s}: mean_dist={mean_dist:.4f}  "
              f"<0.01:{frac_01:.1%}  <0.05:{frac_05:.1%}  <0.10:{frac_10:.1%}")

    # Expected for uniform: if there are K quantum elements in [0,1)^d,
    # a random point is within δ of one of them with prob ≈ K · V_d(δ)
    # where V_d(δ) is the volume of a d-ball of radius δ.
    n_q = len(quantum_elements)
    print(f"\n  Expected for uniform random (K={n_q} elements in [0,1)^{d}):")
    for delta in [0.01, 0.05, 0.10]:
        # Volume of d-ball
        V_d = (math.pi ** (d/2)) / math.gamma(d/2 + 1) * delta**d
        expected = min(1.0, n_q * V_d)
        print(f"    <{delta}: {expected:.4%}")


# =========================================================================
# MAIN
# =========================================================================

if __name__ == "__main__":
    random.seed(42)
    np.random.seed(42)

    from sympy import nextprime

    print(f"{'='*75}")
    print(f"  QUANTUM MICROSCOPE")
    print(f"  Looking at what Regev's algorithm actually produces")
    print(f"{'='*75}")

    # Test cases: small semiprimes where we can enumerate everything
    test_cases = [
        # Small: enumerate all elements
        (7, 11),       # N = 77
        (13, 17),      # N = 221
        (23, 29),      # N = 667
        (31, 37),      # N = 1147
        (59, 61),      # N = 3599
        (101, 103),    # N = 10403
        (127, 131),    # N = 16637
        (251, 257),    # N = 64507
    ]

    for p, q in test_cases:
        N = p * q
        print(f"\n{'='*75}")

        info = build_lattices(N, p, q, d=min(8, len([pr for pr in small_primes(50) if N % pr != 0])))
        if info is None:
            print(f"  Failed to build lattice for N = {N}")
            continue

        elements = enumerate_dual_quotient(info)
        if elements is None or len(elements) == 0:
            print(f"  No elements in L*/Z^d for N = {N}")
            continue

        analyze_quantum_samples(info, elements)

        if len(elements) < 50000:
            compare_classical_to_quantum(info, elements)

    print(f"\n{'='*75}")
    print(f"  FINAL OBSERVATIONS")
    print(f"{'='*75}")
    print(f"""
  The quantum samples (elements of L*/Z^d) are:
  1. Determined entirely by the discrete logs of the bases mod p and mod q
  2. Structured as a finite abelian group whose invariants encode (p-1) and (q-1)
  3. The genus character ε splits them into two halves — only one half factors N
  4. The Jacobi symbols (b_i/N) are computable from N but don't determine
     which half is which — that requires (b_i/p), which requires knowing p

  The quantum advantage: the circuit SAMPLES from this group uniformly,
  without ever explicitly computing the discrete logs or the group structure.
  It does this by exploiting quantum interference in the QFT.

  A classical simulation would need to either:
  (a) Compute the discrete logs (= discrete log problem, equiv to factoring)
  (b) Find the group structure of L*/Z^d without knowing L_R (= factoring)
  (c) Sample from L*/Z^d without knowing its structure (= ???)

  Option (c) is the only one that might be new.
  """)
