#!/usr/bin/env python3
"""
VISUALIZE THE QUANTUM SAMPLES.

d=2 bases. 2D samples on [0,1)². Plot every element of L*/Z^d.
Overlay classical points. LOOK at the picture.
"""

import math
import random
import sys

sys.stdout.reconfigure(line_buffering=True)


def primitive_root(p):
    if p == 2: return 1
    phi = p - 1
    factors = set()
    n = phi
    d = 2
    while d * d <= n:
        while n % d == 0: factors.add(d); n //= d
        d += 1
    if n > 1: factors.add(n)
    for g in range(2, p):
        if all(pow(g, phi // f, p) != 1 for f in factors):
            return g
    return None


def discrete_log(a, g, p):
    a = a % p
    if a == 0: return 0
    cur = 1
    for k in range(p):
        if cur == a: return k
        cur = (cur * g) % p
    return 0


def jacobi_symbol(a, n):
    if n <= 0 or n % 2 == 0: return 0
    a = a % n
    result = 1
    while a != 0:
        while a % 2 == 0:
            a //= 2
            if n % 8 in (3, 5): result = -result
        a, n = n, a
        if a % 4 == 3 and n % 4 == 3: result = -result
        a = a % n
    return result if n == 1 else 0


def generate_and_visualize(p, q, bases):
    N = p * q
    d = len(bases)
    assert d == 2, "Need exactly 2 bases for 2D visualization"

    b1, b2 = bases

    g_p = primitive_root(p)
    g_q = primitive_root(q)
    dlp = [discrete_log(b % p, g_p, p) for b in bases]
    dlq = [discrete_log(b % q, g_q, q) for b in bases]
    genus = [dl % 2 for dl in dlp]

    print(f"N = {N} = {p} × {q}")
    print(f"Bases: {bases}")
    print(f"dlp = {dlp}, dlq = {dlq}")
    print(f"p-1 = {p-1}, q-1 = {q-1}")
    print(f"Genus: {genus}")
    print(f"|L*/Z^d| = {(p-1)*(q-1)}")
    print()

    # Generate ALL quantum samples: w(α,β) for α ∈ Z/(p-1), β ∈ Z/(q-1)
    # w_i = dlp_i · α / (p-1) + dlq_i · β / (q-1) mod 1
    quantum_points = []
    quantum_genus = []  # 0 = even, 1 = odd
    for alpha in range(p - 1):
        for beta in range(q - 1):
            w1 = (dlp[0] * alpha / (p - 1) + dlq[0] * beta / (q - 1)) % 1.0
            w2 = (dlp[1] * alpha / (p - 1) + dlq[1] * beta / (q - 1)) % 1.0
            # Genus parity of this sample
            gp = (genus[0] * alpha + genus[1] * alpha) % 2  # Not quite right
            # Actually genus parity in the DUAL is about the sample's relationship
            # to the factoring coset. For now just track α parity.
            quantum_points.append((w1, w2))
            # A sample factors N iff it's genus-odd
            # genus-odd means Σ w_i * ε_i ≡ 1/2 mod 1 (roughly)
            quantum_genus.append((alpha * genus[0] + alpha * genus[1]) % 2)

    # Generate CLASSICAL points: (b1^k mod N, b2^k mod N) / N
    T = min(5000, (p-1) * (q-1))
    classical_points = []
    v1, v2 = 1, 1
    for k in range(T):
        classical_points.append((v1 / N, v2 / N))
        v1 = (v1 * b1) % N
        v2 = (v2 * b2) % N

    # Also: points from Jacobi-symbol-based construction
    # (b/N) is computable. Use it to color or filter.
    j1 = jacobi_symbol(b1, N)
    j2 = jacobi_symbol(b2, N)

    # Output as ASCII art (since we can't display images)
    # Use a grid
    W, H = 80, 40
    grid_q = [[' '] * W for _ in range(H)]
    grid_c = [[' '] * W for _ in range(H)]
    grid_both = [[' '] * W for _ in range(H)]

    # Plot quantum points
    for w1, w2 in quantum_points:
        x = int(w1 * (W - 1))
        y = int(w2 * (H - 1))
        x = min(x, W - 1)
        y = min(y, H - 1)
        grid_q[H - 1 - y][x] = '·'
        grid_both[H - 1 - y][x] = '·'

    # Plot classical points (overwrite with different symbol)
    for w1, w2 in classical_points[:2000]:
        x = int(w1 * (W - 1))
        y = int(w2 * (H - 1))
        x = min(x, W - 1)
        y = min(y, H - 1)
        grid_c[H - 1 - y][x] = '×'
        if grid_both[H - 1 - y][x] == '·':
            grid_both[H - 1 - y][x] = '⊕'  # overlap
        else:
            grid_both[H - 1 - y][x] = '×'

    print(f"QUANTUM SAMPLES ({len(quantum_points)} points) — each · is an element of L*/Z^2")
    print(f"+" + "-" * W + "+")
    for row in grid_q:
        print(f"|{''.join(row)}|")
    print(f"+" + "-" * W + "+")

    print(f"\nCLASSICAL ORBIT (b^k mod N)/N for k=0..{min(T,2000)} — each × is a classical point")
    print(f"+" + "-" * W + "+")
    for row in grid_c:
        print(f"|{''.join(row)}|")
    print(f"+" + "-" * W + "+")

    print(f"\nOVERLAY: · = quantum only, × = classical only, ⊕ = both")
    print(f"+" + "-" * W + "+")
    for row in grid_both:
        print(f"|{''.join(row)}|")
    print(f"+" + "-" * W + "+")

    # Higher resolution: dump coordinates for the TRUE p,q pair
    # and nearby quantum points
    print(f"\n--- QUANTUM POINT STRUCTURE ---")
    print(f"Quantum points form a lattice on the torus [0,1)²")
    print(f"The lattice is generated by two vectors:")
    v_alpha = ((dlp[0] / (p-1)) % 1.0, (dlp[1] / (p-1)) % 1.0)
    v_beta = ((dlq[0] / (q-1)) % 1.0, (dlq[1] / (q-1)) % 1.0)
    print(f"  v_α = ({v_alpha[0]:.6f}, {v_alpha[1]:.6f})  [step in α direction]")
    print(f"  v_β = ({v_beta[0]:.6f}, {v_beta[1]:.6f})  [step in β direction]")
    print(f"  (p-1) steps of v_α = identity, (q-1) steps of v_β = identity")

    # The classical orbit traces a 1D path through this 2D lattice
    # The path is: (α, β) = (k·dlog_p(b1), k·dlog_q(b1)) for the first base
    # Wait, that's for a single base. For two bases, the classical orbit is
    # (b1^k/N, b2^k/N) which is a 2D point for each k.
    # In the quantum parametrization: this corresponds to
    # α = k (the "exponent" mod p-1) and β = k (mod q-1).
    # So the classical orbit is the DIAGONAL path α = β·(something).

    # More precisely: b1^k mod p = g_p^{k·dlp[0]} mod p
    # So the "α" for the classical orbit at step k is: k·dlp[0] mod (p-1)
    # And the "β" is: k·dlq[0] mod (q-1)
    # The classical orbit visits (α, β) = (k·dlp[0] mod (p-1), k·dlq[0] mod (q-1))

    print(f"\n--- CLASSICAL ORBIT IN (α,β) SPACE ---")
    print(f"Classical step k gives (α,β) = ({dlp[0]}k mod {p-1}, {dlq[0]}k mod {q-1})")
    print(f"This is a 1D orbit on the 2D torus Z/(p-1) × Z/(q-1)")
    print(f"The orbit has period lcm(ord_p(b1), ord_q(b1))")

    ord_p1 = (p - 1) // math.gcd(dlp[0], p - 1)
    ord_q1 = (q - 1) // math.gcd(dlq[0], q - 1)
    print(f"  ord_p({b1}) = {ord_p1}, ord_q({b1}) = {ord_q1}")
    print(f"  orbit period = lcm = {ord_p1 * ord_q1 // math.gcd(ord_p1, ord_q1)}")

    # The key observation: the classical orbit visits (p-1)×(q-1)/period fraction
    # of all quantum points. If the orbit is dense (period close to (p-1)(q-1)),
    # classical sees almost everything. If sparse, it misses most.

    period = ord_p1 * ord_q1 // math.gcd(ord_p1, ord_q1)
    coverage = period / ((p-1) * (q-1))
    print(f"  classical coverage: {period}/{(p-1)*(q-1)} = {coverage:.4f} of quantum points")

    # CRITICAL: what's the SLOPE of the classical orbit?
    # In (α,β) space, each step adds (dlp[0], dlq[0]).
    # The slope is dlq[0]/dlp[0] mod ... but this is in a discrete torus.
    # The slope = dlq[0] * inverse(dlp[0]) mod (q-1)... no, it's on a product of two cyclic groups.
    # The ratio dlq[0]/dlp[0] is the "exchange rate" between p-info and q-info.
    # A classical observer sees this ratio but can't decompose it.

    print(f"\n--- WHAT CLASSICAL CAN vs CANNOT SEE ---")
    print(f"Classical sees: the 1D orbit (b1^k/N, b2^k/N) = projections of (α,β) path")
    print(f"Classical CANNOT see: which direction is 'α' and which is 'β'")
    print(f"  because α and β are defined by discrete logs mod p and q separately.")
    print(f"  Separating them = factoring.")
    print(f"")
    print(f"Jacobi symbols (computable from N):")
    print(f"  ({b1}/N) = {j1}  ({b2}/N) = {j2}")
    print(f"  ({b1}/p) = {1 if dlp[0]%2==0 else -1}  ({b1}/q) = {1 if dlq[0]%2==0 else -1}")
    print(f"  ({b2}/p) = {1 if dlp[1]%2==0 else -1}  ({b2}/q) = {1 if dlq[1]%2==0 else -1}")


if __name__ == "__main__":
    random.seed(42)

    # Small example where we can see everything
    print("=" * 82)
    print("  VISUALIZING QUANTUM vs CLASSICAL: THE PICTURE")
    print("=" * 82)
    print()

    # 12-bit semiprime with d=2 bases
    generate_and_visualize(37, 41, [2, 3])

    print("\n\n")
    print("=" * 82)

    # Slightly larger
    generate_and_visualize(101, 103, [2, 3])

    print("\n\n")
    print("=" * 82)

    # 16-bit
    generate_and_visualize(137, 157, [2, 3])
